import asyncio
import logging
import uuid
from datetime import datetime
from typing import Dict, Any, List

from core.llm_client import LLMClient
from db.local_database import LocalDatabase
from agents.main_agent import MainAgent
from agents.rom_main_agent import RomMainAgent
from agents.rom_sub_agent import RomSubAgent

logger = logging.getLogger(__name__)

class Orchestrator:
    """
    Manages the lifecycle, recurrent feedback loops, and parallel Scatter-Gather executions
    for the 3-tier LLM-ROM Architecture, enforcing _a, _b, _c hierarchical ID logging.
    """
    def __init__(self):
        # Initialize LLM clients with the models defined in the specification
        self.heavy_llm_client = LLMClient(model="z-ai/glm-5")
        self.light_llm_client = LLMClient(model="openai/gpt-oss-120b")
        
        # Instantiate the new LocalDatabase
        self.db = LocalDatabase()
        
        # Initialize the 3 tiers
        self.main_agent = MainAgent(self.heavy_llm_client)
        self.rom_main = RomMainAgent(self.heavy_llm_client)
        self.rom_sub = RomSubAgent(self.light_llm_client, self.db)
        
        # State for a single session
        self.session_context = {}
    
    async def run(self, user_input: str):
        # Generate base ID for this session/interaction: YYYYMMDD-HH-MM-SS format
        base_id = datetime.now().strftime("%Y%m%d-%H-%M-%S")
        logger.info(f"Starting new interaction cycle with Base ID: {base_id}")
        
        # Save user input context to DB as the start of the interaction
        self.db.save_agent_log(f"{base_id}_user", "system", {"user_input": user_input})
        
        # 1. Main Agent Input Construction
        # Since Main Agent remembers its own thought history, we only send context and input once per turn.
        main_input = {
            "user_input": user_input,
            "session_context": self.session_context
        }

        # MAIN AGENT LOOP
        while True:
            # Main Agent Output _a
            main_json, raw_main = await self.main_agent.process(main_input)
            action = main_json.get("action_type")
            
            # Persist Main Agent Output into a single isolated file with _a suffix
            main_log_id = f"{base_id}_a"
            main_json["log_id"] = main_log_id # Force attach the generated ID internally
            main_json["raw_cot"] = raw_main   # Embed full internal reasoning
            self.db.save_agent_log(main_log_id, "main", main_json)
            
            if action == "reply_to_user":
                # Final output to user
                logger.info(f"\n[System Output] {main_json.get('reply_content')}")
                self.session_context = main_json.get("session_context", self.session_context)
                break
            
            elif action == "request_investigation":
                reply = main_json.get("reply_content", "")
                if reply:
                    logger.info(f"\n[System Thinking...] {reply}")
                
                reqs = main_json.get("investigation_requests", [])
                current_turn_rom_results = []
                
                # Iterate each request generated by Main Agent
                for req_idx, req in enumerate(reqs, start=1):
                    rom_b_id = f"{base_id}_b{req_idx}"
                    req["request_id"] = rom_b_id  # Emphasize mapping the requested ID
                    
                    # 2. Transition into ROM Main Agent Loop defined per Request
                    rom_main_input = {
                        "session_context": self.session_context,
                        "investigation_request": req
                    }
                    
                    # Reset ROM Main's memory for each separate investigation request
                    self.rom_main.reset_memory()
                    
                    while True:
                        rom_main_json, raw_rom_main = await self.rom_main.process(rom_main_input)
                        rom_action = rom_main_json.get("action_type")
                        
                        # Save ROM Main event per request: XXXXXXX_b{N}
                        rom_b_log_id = f"{rom_b_id}"
                        rom_main_json["request_id"] = rom_b_log_id
                        rom_main_json["raw_cot"] = raw_rom_main # Embed full internal reasoning
                        self.db.save_agent_log(rom_b_log_id, "rom_main", rom_main_json)
                        
                        if rom_action == "report_to_main":
                            report = rom_main_json.get("final_report_to_main")
                            logger.info(f"\n[ROM Main -> Main] Final Report Submitted for {rom_b_id}.")
                            current_turn_rom_results.append({"request_id": rom_b_id, "report": report})
                            break
                            
                        elif rom_action == "dispatch_sub_tasks":
                            sub_tasks = rom_main_json.get("sub_tasks", [])
                            logger.info(f"\n[ROM Main {rom_b_id}] Dispatching {len(sub_tasks)} scattered sub-tasks...")
                            
                            # Give proper contextual internal DB IDs to the sub tasks
                            for st_idx, st in enumerate(sub_tasks, start=1):
                                st["task_id"] = f"{rom_b_id}_c{st_idx}"
                            
                            # 3. Scatter-Gather Parallel Execution for ROM Sub Agents
                            tasks = [self.rom_sub.process(st) for st in sub_tasks]
                            sub_results = await asyncio.gather(*tasks)
                            
                            # Save each Sub Agent single report: XXXXX_b{N}_c{M}
                            for sub_res in sub_results:
                                sub_task_id = sub_res.get("task_id", f"{rom_b_id}_c_unknown")
                                self.db.save_agent_log(sub_task_id, "rom_sub", sub_res)
                            
                            rom_main_input = {
                                "sub_agent_reports": sub_results
                            }
                        else:
                            break
                        
                # Update Main Agent's input with JUST the findings from THIS turn, 
                # as it already remembers previous context in its self.messages history.
                main_input = {
                    "rom_investigation_results": current_turn_rom_results
                }
            else:
                logger.error(f"Unknown Main Agent action: {action}")
                break
